load locatable .
omod INTERSECTION is
    protecting LOCATABLE .
    protecting STRING .
    class Intersection | neighbors : OidSet .
    subclass Intersection < Locatable .

    op oid : Object -> Oid .

    vars S S' : String .
    vars L L' : Location .

    eq oid(< S : Intersection | >) = S .
    eq distance(< S : Intersection | location : L >, < S' : Intersection | location : L' >) = distance(L, L') .
endom
