load location .
fmod PATH is
    protecting LOCATION .
    protecting INT .

    sort Path .

    op nil : -> Path [ctor] .
    op {__} : Location Location -> Path [ctor] .
    op __ : Path Path -> Path [ctor assoc] .

    op overlap : Path Path -> Location [comm] .

    vars X X2 X3 Y Y2 Y3 : Int .

    ***Vertical overlap
    ***eq overlap({(X,Y) (X,Y2)}, {(X3,Y3) (X3,Y4)}) = if  fi .
    
endfm
